In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

In [9]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward 
        
        if done == True: 
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.2570000000000002
2000 :  1.0109999999999995
3000 :  1.2949999999999682
4000 :  1.3669999999999602
5000 :  1.3809999999999587
6000 :  0.23900000000000018
7000 :  0.9680000000000007
8000 :  1.2749999999999704
9000 :  1.360999999999961
10000 :  1.3129999999999662


In [10]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.51439247 0.5007446  0.50299106 0.503346  ]
 [0.31643753 0.37327493 0.39903693 0.48370994]
 [0.37528564 0.41264553 0.39123596 0.46010598]
 [0.33968627 0.3023918  0.27959635 0.45134135]
 [0.54037234 0.38262996 0.33440758 0.28429466]
 [0.         0.         0.         0.        ]
 [0.23872691 0.14483492 0.177503   0.1705587 ]
 [0.         0.         0.         0.        ]
 [0.41869885 0.51583114 0.43288597 0.57691338]
 [0.37042665 0.6161849  0.38607748 0.39901988]
 [0.4546691  0.490514   0.35576977 0.27650996]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51140204 0.43820618 0.74069929 0.47899913]
 [0.72688221 0.85839578 0.74905078 0.77143963]
 [0.         0.         0.         0.        ]]


In [12]:
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        # Choose action with highest Q-value for current state  
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        # Take new action

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break  
        state = new_state  

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
